### PR TITLE
Use bio-formats to determine file type where possible 

### PR DESCRIPTION
**Pull request by imunro**
see https://github.com/imperial-photonics/FLIMfit/issues/163 and  /182

### CODE REVIEW

**Comment by imunro** [comment]
@seanwarren this will fix both of the above issues but maybe not in a way that you're happy with ?

**Comment by imunro** [comment]
Trigger build

**Comment by imunro** [comment]
@seanwarren I've tried closing all 2 open PRs in turn and I'm still getting the same errors from the win-merge build. If you have any thought that would really help. I've no idea what the error messages are telling me.

**Comment by seanwarren** [comment]
@imunro I think I've resolved this now -  the antivirus on the build computer was seriously messing stuff up. the ffd merge is working now, and the OME52 is running ok so far

**Comment by imunro** [comment]
Many thanks Sean

I was way out of my depth. I need to work out what’s going on with that Windows build but starting when it was being so flakey anyway I  wasn’t getting anywhere.


Ian


On 10 Mar 2016, at 08:49, Sean Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


@imunro<https://github.com/imunro> I think I've resolved this now - the antivirus on the build computer was seriously messing stuff up. the ffd merge is working now, and the OME52 is running ok so far

**Comment by imunro** [comment]
Merging to test in conjunction with .bin FLIMreader

**Pull request merged**
