### PR TITLE
Enable version checking on FLIMfit start

### PR DESCRIPTION
**Pull request by seanwarren**
Create a dialog box if new version is available pointing to download page

### CODE REVIEW

**Comment by seanwarren** [comment]
@imunro - what do you think of this? might be quite useful

**Comment by imunro** [comment]
Version FLIMfit 4.10.3-72-g64dd246.app  (mac) Outputs a lot of extra lines to the test window.
Looks like the name of all the front-end menu items.

screen shot 2016-03-18 at 16 36 17

**Comment by seanwarren** [comment]
@imunro , sorry left some debugging stuff in. That should be fixed now. It checks flimfit.org/current-version.txt and displays a message if there is a new version, if you run it now it should show the message as I've updated current-version.txt for testing

**Comment by imunro** [comment]
Just did a v.quick test. Looks good. If you're off-line a couple of errors appear in the text window but I don't have a problem with that.
I"ll try and test more thoroughly later but basically happy to merge.

**Comment by seanwarren** [comment]
Cool those are in a try catch block so we can turn them off easily if we want. Let's do a release candidate tomorrow and try and release on Wed?

NOTICE
Please consider the environment before printing this email. This message and any attachments are intended for the addressee named and may contain legally privileged/confidential/copyright information. If you are not the intended recipient, you should not read, use, disclose, copy or distribute this communication. If you have received this message in error please notify us at once by return email and then delete both messages. We accept no liability for the distribution of viruses or similar in electronic communications. This notice should not be removed.

**Comment by imunro** [comment]
Would be good if I wasn't leaving for Easter  holiday on Wed. May have to wait for my return now.

**Pull request merged**
