### PR TITLE
Import workaround

### PR DESCRIPTION
**Pull request by seanwarren**

### CODE REVIEW

**Comment by seanwarren** [comment]
@imunro @Neseb I've tried to cherry pick the relevant commits from this branch, can you let me know if I've missed anything?

@imunro - is this intended for the next release

**Comment by seanwarren** [comment]
trigger build

**Comment by imunro** [comment]
@seanwarren There's no intention to merge these changes into the FLIMfit repo at all.
This was a temporary fix for an internal Photonics issue and the changes should remain in Neseb's fork only. The PR is simply in order to use your CI to build.

**Comment by imunro** [comment]
@seanwarren I suggest deleting this branch - I can do it if you're happy.

**Pull request closed without merging**
