### PR TITLE
Omero52

### PR DESCRIPTION
**Pull request by imunro**
Mods to allow FLIMfit to work with OMERO 5.2 and with the current OMEuiUtils.

### CODE REVIEW

**Comment by imunro** [comment]
@seanwarren What do you think about merging this. Only a couple of tiny changes could possibly affect the file-side.

**Comment by seanwarren** [comment]
Trigger build

**Comment by seanwarren** [comment]
@imunro looks good, I've just re-triggered the CI integration checks so will merge if they complete successfully

**Comment by imunro** [comment]
I'm not sure what, if anything, these checks are telling me. Tempted to go ahead and merge as the mac merge build looks ok now.

**Comment by seanwarren** [comment]
HI Ian, they are saying whether the builds worked (click on Details to go through to the CI server).

**Comment by seanwarren** [comment]
Trigger Build

**Comment by seanwarren** [comment]
Trigger build

**Comment by imunro** [comment]
Ok nothing I didn't know then. Thanks. I'm a bit stuck on the win-merge problem. It looks like a recurrrence of the problem I had on terminalsix (missing windows patch) but it can't be.

**Comment by imunro** [comment]
and how do you trigger the merge builds manually?

**Comment by seanwarren** [comment]
Just write a comment 'Trigger build'. Should work for admin accounts

**Comment by seanwarren** [comment]
I think there might be something up on the build machine - will look tomorrow if poss

**Comment by imunro** [comment]
Thanks Sean. In the meantime is it ok to merge so I can make sure latest-mac works ok ?

**Comment by imunro** [comment]
Trigger build

**Comment by imunro** [comment]
Trigger build

**Comment by imunro** [comment]
closing to try and establish whether this is causing win_merge to fail

**Comment by seanwarren** [comment]
Trigger build

**Comment by seanwarren** [comment]
Trigger build

**Comment by seanwarren** [comment]
Trigger build

**Comment by imunro** [comment]
Merging as I can't see how this one could give you a problem @seanwarren and it'll mean I can check out the "latest" builds.

**Pull request merged**
