### PR TITLE
Revert "Fix segmentation manager layout"

### PR DESCRIPTION
**Pull request by imunro**
This reverts commit 0252b05aed22d254327cdbc33c468f47173d1226.
Apparently the segmentation has been un-readable, at least on macs, since this commit.
Reverting to check function on Win 7.

### CODE REVIEW

**Comment by imunro** [comment]
@seanwarren  Just so you know what's going on ... apparently the non-working segmentation tool (most of the buttons don't fit in the window) is holding people up so I'm iterating  to get a quick fix in place (I know a new version is on it's way).  Very frustrating as the ones that work on the mac don't on Windows & vice-verse.

**Comment by imunro** [comment]
@seanwarren Getting closer but I still can't get the display area to sit anywhere sensible on Windows.
What do you think to a cut/paste solution with sementation_manager_m & segmentation_manager_w as a stop-gap until 5.0 is ready? It looks like you sensibly avoided Guide for that.

**Comment by seanwarren** [comment]
@imunro - if that's the only way you can get the layouts to work then I guess so!

**Comment by imunro** [comment]
Well I could re-write in something that works cross-platform (e.g. Java Swing) but a) I haven't got time b) I suspect you're already working on thsi.

**Comment by imunro** [comment]
Failed to get a working version!

**Pull request closed without merging**
