### PR TITLE
Merge 5.0 branch into master

### PR DESCRIPTION
**Pull request by seanwarren**

### CODE REVIEW

**Comment by imunro** [comment]
@seanwarren I take it that we've moved to Matlab 2016b ?

**Comment by seanwarren** [comment]
Just testing it out for the build servers - no need to upgrade if you don't want to

**Comment by imunro** [comment]
Ok Let me know if you do want to upgrade.

**Comment by seanwarren** [comment]
Cool, I guess we will go that way sooner rather than later. The build scripts will still respect the MATLAB_VER variable as well

**Pull request merged**
