### PR TITLE
Allow metadata extraction from filenames when using MD data

### PR DESCRIPTION
**Pull request by seanwarren**

### CODE REVIEW

**Comment by seanwarren** [comment]
Trigger build

**Comment by seanwarren** [comment]
Trigger build

**Comment by seanwarren** [comment]
Trigger build

**Comment by imunro** [comment]
I haven't had a chance to look at the code yet but one possible issue occurs: I use sort_nat on the selected files but with such complex file names there seems to be a danger of the extracted metadata being in the "wrong" order. I guess this just files under "sort your file names out" ?

**Comment by seanwarren** [comment]
Well I guess that is no more or less of an issue than it currently is. Ideally I think it would be good to be able to sort the displayed results based on the metadata rather than messing around with it at load time

**Comment by imunro** [comment]
Code looks good to me (especially where you got rid of that nasty switch). Only suggestion is that the add_class subroutine (last few lines of select_multiple) should be deleted now that it's no longer used.
Otherwise happy to merge.

**Comment by imunro** [comment]
On a second look I think the behaviour has changed and the line any(cellfun(@length,ZCT) > allowed)
means that metadata will be set for all 3 dimensions rather than just the one that's greater than allowed.

**Comment by seanwarren** [comment]
I've cleaned this up a little now as the loop was unnecessary - I hadn't quite clocked that only one dimension can be iterated over. I'm going to use this branch for a bit to test but I think we're good to merge

**Comment by imunro** [comment]
That looks much neater now. The GUI should ensure that > allowed can only be selected in one dimension. NB this work could be moved into extract_metadata if preferred.

**Comment by seanwarren** [comment]
OK cheers, I think this is ok for now

**Pull request merged**
