### PR TITLE
Add a size threshold to "transforming" waitbar.

### PR DESCRIPTION
**Pull request by imunro**

### CODE REVIEW

**Comment by imunro** [comment]
@seanwarren Does this look better? Also Matlab is telling me that lines 160 -167 in compute_tr_data aren't doing anything (they are all to set "sel' which then isn't used).
I'm reluctant to change that just before a release but maybe you're more familiar with this code?

**Comment by imunro** [comment]
@seanwarren the last 2 commits are just cosmetic. Is this good enough for you to be happy to release?

**Comment by seanwarren** [comment]
@imunro - sorry about the radio silence, we moved house over the weekend! Yes this looks good to me.

**Comment by imunro** [comment]
NP I figured it was something like that. Hope it went ok. I'll do a quick smoke-test of the release again & then, hopefully we're good to go.

**Comment by imunro** [comment]
Looks like flimfit-release-win job has fallen over. Seem sit can't find the .dll which I've definitely seen before - sadly I can't remember the fix ?

**Pull request merged**
