### PR TITLE
Use 16 segmentation masks

### PR DESCRIPTION
**Pull request by seanwarren**
To fix bug #223

### CODE REVIEW

**Comment by seanwarren** [comment]
@imunro - any OMERO implications here you can see?

**Comment by imunro** [comment]
Good point. I'll have a look as soon as I can.

**Comment by imunro** [comment]
No OMERO implications that I can see and a quick test seemed fine. The possible exception being the shift from channel:n  to channel n I have a vague memory of choosing :n  for  some  particular reason (I suspect  it's what bio-formats returns if the channel info is set?) but also parsing for spaces is generally a nightmare.

**Comment by imunro** [comment]
Oh also it might be good to merge https://github.com/imperial-photonics/FLIMfit/pull/218 first if  you're happy with it or things might start to get messy.

**Pull request merged**
